server:
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    # YouTube Source plugin
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
    # Spotify Source plugin
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "ProphetLava_2026_A7mQ!4sK9x"
    sources:
      youtube: false # We use the plugin instead
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 2000
    youtubePlaylistLoadLimit: 100
    playerUpdateInterval: 2
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - ANDROID_MUSIC
      - ANDROID_VR
      - TVHTML5_SIMPLY
      - IOS
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\"" 
      - "ytsearch:%QUERY%" 
    sources:
      spotify: true
      applemusic: true
      deezer: false
      yandexmusic: false
    spotify:
      clientId: "c730c72d421c4011a9687a13098a52d4"
      clientSecret: "ee92bb60ae00469da5eb9b1f3a456564"
      countryCode: "US"
logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
